### ISSUE TITLE
help with loading the font

### ISSUE THREAD

**Issue by Only-Moon** [tarannagra/windots#1]
I downloaded them from the official nerd website and one by one installed all of the ones inside the zip file through the default Windows font installer, but it doesn't look the same way as yours

I'm using your exact same file - version 2

result - 
![image](https://github.com/tarannagra/windots/assets/75924613/446574fc-5b56-4ad5-b0ec-81760d199670)

**Comment by Only-Moon** [comment]
made it to work using icons from https://www.nerdfonts.com/cheat-sheet . you should check into that

![image](https://github.com/tarannagra/windots/assets/75924613/35e1d657-c17f-4145-a4c1-aa5493111c48)

**Comment by tarannagra** [comment]
Oh that's interesting. I've not seen that issue before.

I'm currently away on a holiday for 2 weeks, so when I'm back, I will address it in the README or create a fix if I can find one.

**Comment by tarannagra** [comment]
Issued addressed in the README.

**Comment by tarannagra** [comment]
Updated! Thanks for letting me know about this. 

See this [commit](https://github.com/tarannagra/windots/commit/a9f3b617bad9e29e5d9082dcb2502070189e3907) for the updated version.
